packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/tengo-builder': ^1.17.5
  '@platforma-sdk/block-tools': ^2.5.9

  '@platforma-sdk/workflow-tengo': ^2.9.9
  '@platforma-sdk/model': ^1.22.18
  '@platforma-sdk/test': ^1.22.22

  '@milaboratories/graph-maker': ^1.1.37
  '@platforma-sdk/ui-vue': ^1.22.19
  '@milaboratories/helpers': ^1.6.11
  '@milaboratories/software-pframes-conv': ^1.5.6

  'sass': ^1.83.4

  'vue': ^3.5.13
  'vue-tsc': ^2.2.0

  'zod': ^3.23.8

  'typescript': ^5.5.4
  'tsup': ~8.3.5
  'turbo': ^2.3.3

  'vite': ^5.4.10
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1

  '@changesets/cli': ^2.27.12
