packages:
  - workflow
  - model
  - ui
  - .
  - test

catalog:
  "@platforma-sdk/tengo-builder": ^1.15.1
  "@platforma-sdk/block-tools": ^2.3.19

  "@platforma-sdk/workflow-tengo": ^1.6.4
  "@platforma-sdk/model": ^1.7.20
  "@platforma-sdk/test": ^1.7.21

  "@milaboratories/uikit": ^1.2.28
  "@milaboratories/graph-maker": ^1.0.16
  "@platforma-sdk/ui-vue": ^1.7.22
  "@milaboratories/helpers": ^1.6.6
  "@milaboratories/software-pframes-conv": ^1.5.6

  "sass": ^1.80.4

  "vue": ^3.5.12
  "vue-tsc": ^2.1.8

  "zod": ^3.23.8

  "typescript": ^5.5.4
  "tsup": ~8.3.5

  "vite": ^5.4.10
  "vitest": ^2.1.4
  "@vitejs/plugin-vue": ^5.1.0

  "@changesets/cli": ^2.27.9
