packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/tengo-builder': ^2.0.3
  '@platforma-sdk/block-tools': ^2.5.35


  '@platforma-sdk/workflow-tengo': ^4.0.4
  '@platforma-sdk/model': ^1.28.4
  '@platforma-sdk/test': ^1.28.6


  '@milaboratories/graph-maker': ^1.1.70
  '@platforma-sdk/ui-vue': ^1.28.4
  '@milaboratories/helpers': ^1.6.11
  '@milaboratories/software-pframes-conv': ^1.5.6

  'sass': ^1.86.3

  'vue': ^3.5.13
  'vue-tsc': ^2.2.8

  'zod': ^3.23.8

  'typescript': ^5.8.2
  'tsup': ~8.3.5
  'turbo': ^2.5.0

  'vite': ^5.4.10
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.3

  '@changesets/cli': ^2.28.1
