packages:
  - workflow
  - model
  - ui
  - .
  - test

catalog:
  "@platforma-sdk/tengo-builder": ^1.14.11
  "@platforma-sdk/block-tools": ^2.1.11

  "@platforma-sdk/workflow-tengo": ^1.2.8
  "@platforma-sdk/model": ^1.2.26
  "@platforma-sdk/test": ^1.5.15

  "@milaboratories/uikit": ^1.2.7
  "@milaboratory/graph-maker": ^1.0.0
  "@platforma-sdk/ui-vue": ^1.3.7
  "@milaboratories/helpers": ^1.6.2
  "@milaboratories/software-pframes-conv": ^1.5.6

  "sass": ^1.69.0

  "vue": ^3.4.34
  "vue-tsc": ^2.0.29

  "zod": ^3.23.8

  "typescript": ^5.5.4
  "tsup": ~8.1.2

  "vite": ^5.3.5
  "vitest": ^2.0.4
  "@vitejs/plugin-vue": ^5.1.0

  "@changesets/cli": ^2.27.7
