packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@milaboratories/ts-configs': ^1.0.5
  '@milaboratories/build-configs': ^1.0.5
  '@platforma-sdk/tengo-builder': ^2.1.14
  '@platforma-sdk/block-tools': ^2.5.80
  '@platforma-sdk/workflow-tengo': ^4.17.0
  '@platforma-sdk/model': ^1.42.10
  '@platforma-sdk/test': ^1.42.12
  '@milaboratories/graph-maker': ^1.1.142
  '@platforma-sdk/ui-vue': ^1.42.10
  '@milaboratories/helpers': ^1.6.19
  '@milaboratories/software-pframes-conv': ^1.5.6

  'sass': ^1.89.2

  'vue': ^3.5.17
  'vue-tsc': ^2.2.10

  'zod': ^3.23.8

  'typescript': ^5.8.3
  'tsup': ~8.3.5
  'turbo': ^2.5.5

  'vite': ^6.3.5
  'vitest': ^3.1.3
  '@vitejs/plugin-vue': ^5.2.4

  '@changesets/cli': ^2.29.5
