packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@milaboratories/ts-configs': ^1.0.6
  '@milaboratories/build-configs': ^1.0.8
  '@platforma-sdk/tengo-builder': ^2.1.18
  '@platforma-sdk/block-tools': ^2.5.83
  '@platforma-sdk/workflow-tengo': ^5.1.2
  '@platforma-sdk/model': ^1.42.47
  '@platforma-sdk/test': ^1.42.48
  '@milaboratories/graph-maker': ^1.1.154
  '@platforma-sdk/ui-vue': ^1.42.47
  '@milaboratories/helpers': ^1.7.0
  '@milaboratories/software-pframes-conv': ^1.5.6

  'sass': ^1.89.2

  'vue': ^3.5.17
  'vue-tsc': ^3.0.5

  'zod': ^3.23.8

  'typescript': ^5.9.2
  'tsup': ~8.3.5
  'turbo': ^2.5.5

  'vite': ^7.1.2
  'vitest': ^3.2.4
  '@vitejs/plugin-vue': ^6.0.1

  '@changesets/cli': ^2.29.6
