packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/tengo-builder': ^2.1.10
  '@platforma-sdk/block-tools': ^2.5.55


  '@platforma-sdk/workflow-tengo': ^4.8.0
  '@platforma-sdk/model': ^1.37.0
  '@platforma-sdk/test': ^1.37.0


  '@milaboratories/graph-maker': ^1.1.123
  '@platforma-sdk/ui-vue': ^1.36.0
  '@milaboratories/helpers': ^1.6.12
  '@milaboratories/software-pframes-conv': ^1.5.6

  'sass': ^1.89.2

  'vue': ^3.5.14
  'vue-tsc': ^2.2.10

  'zod': ^3.23.8

  'typescript': ^5.8.3
  'tsup': ~8.3.5
  'turbo': ^2.5.4

  'vite': ^6.3.5
  'vitest': ^3.1.3
  '@vitejs/plugin-vue': ^5.2.4

  '@changesets/cli': ^2.29.4
