packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/tengo-builder': ^2.1.6
  '@platforma-sdk/block-tools': ^2.5.51


  '@platforma-sdk/workflow-tengo': ^4.6.5
  '@platforma-sdk/model': ^1.32.1
  '@platforma-sdk/test': ^1.32.6


  '@milaboratories/graph-maker': ^1.1.106
  '@platforma-sdk/ui-vue': ^1.32.2
  '@milaboratories/helpers': ^1.6.11
  '@milaboratories/software-pframes-conv': ^1.5.6

  'sass': ^1.89.0

  'vue': ^3.5.14
  'vue-tsc': ^2.2.10

  'zod': ^3.23.8

  'typescript': ^5.8.3
  'tsup': ~8.3.5
  'turbo': ^2.5.3

  'vite': ^6.3.5
  'vitest': ^3.1.3
  '@vitejs/plugin-vue': ^5.2.4

  '@changesets/cli': ^2.29.4
