packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/tengo-builder': ^2.1.3
  '@platforma-sdk/block-tools': ^2.5.44


  '@platforma-sdk/workflow-tengo': ^4.3.0
  '@platforma-sdk/model': ^1.30.11
  '@platforma-sdk/test': ^1.30.8


  '@milaboratories/graph-maker': ^1.1.84
  '@platforma-sdk/ui-vue': ^1.30.15
  '@milaboratories/helpers': ^1.6.11
  '@milaboratories/software-pframes-conv': ^1.5.6

  'sass': ^1.87.0

  'vue': ^3.5.13
  'vue-tsc': ^2.2.10

  'zod': ^3.23.8

  'typescript': ^5.8.3
  'tsup': ~8.3.5
  'turbo': ^2.5.2

  'vite': ^5.4.10
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.3

  '@changesets/cli': ^2.29.3
