packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@milaboratories/ts-configs': ^1.0.6
  '@milaboratories/build-configs': ^1.0.8
  '@platforma-sdk/tengo-builder': ^2.3.0
  '@platforma-sdk/block-tools': ^2.6.8
  '@platforma-sdk/workflow-tengo': ^5.3.3
  '@platforma-sdk/model': ^1.43.21
  '@platforma-sdk/test': ^1.44.7
  '@milaboratories/graph-maker': ^1.1.164
  '@platforma-sdk/ui-vue': ^1.43.21
  '@milaboratories/helpers': ^1.9.0
  '@milaboratories/software-pframes-conv': ^2.2.7
  '@platforma-sdk/blocks-deps-updater': ^2.0.0

  'sass': ^1.89.2

  'vue': ^3.5.17
  'vue-tsc': ^3.0.5

  'zod': ^3.23.8

  'typescript': ^5.9.2
  'tsup': ~8.3.5
  'turbo': ^2.5.5

  'vite': ^7.1.2
  'vitest': ^3.2.4
  '@vitejs/plugin-vue': ^6.0.1

  '@changesets/cli': ^2.29.7
