packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/tengo-builder': ^1.17.3
  '@platforma-sdk/block-tools': ^2.5.1

  '@platforma-sdk/workflow-tengo': ^2.7.0
  '@platforma-sdk/model': ^1.20.27
  '@platforma-sdk/test': ^1.20.29

  '@milaboratories/graph-maker': ^1.1.19
  '@platforma-sdk/ui-vue': ^1.20.30
  '@milaboratories/helpers': ^1.6.11
  '@milaboratories/software-pframes-conv': ^1.5.6

  'sass': ^1.80.6

  'vue': ^3.5.13
  'vue-tsc': ^2.1.10

  'zod': ^3.23.8

  'typescript': ^5.5.4
  'tsup': ~8.3.5
  'turbo': ^2.3.3

  'vite': ^5.4.10
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1

  '@changesets/cli': ^2.27.10
