packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/tengo-builder': ^1.19.2
  '@platforma-sdk/block-tools': ^2.5.18

  '@platforma-sdk/workflow-tengo': ^2.15.4
  '@platforma-sdk/model': ^1.22.59
  '@platforma-sdk/test': ^1.22.84

  '@milaboratories/graph-maker': ^1.1.53
  '@platforma-sdk/ui-vue': ^1.22.59
  '@milaboratories/helpers': ^1.6.11
  '@milaboratories/software-pframes-conv': ^1.5.6

  'sass': ^1.85.1

  'vue': ^3.5.13
  'vue-tsc': ^2.2.8

  'zod': ^3.23.8

  'typescript': ^5.5.4
  'tsup': ~8.3.5
  'turbo': ^2.4.4

  'vite': ^5.4.10
  'vitest': ^2.1.8
  '@vitejs/plugin-vue': ^5.2.1

  '@changesets/cli': ^2.28.1
