packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  "@platforma-sdk/tengo-builder": ^1.17.3
  "@platforma-sdk/block-tools": ^2.4.11

  "@platforma-sdk/workflow-tengo": ^2.8.1
  "@platforma-sdk/model": ^1.20.0
  "@platforma-sdk/test": ^1.14.9

  "@milaboratories/graph-maker": ^1.1.9
  "@platforma-sdk/ui-vue": ^1.20.4
  "@milaboratories/helpers": ^1.6.10
  "@milaboratories/software-pframes-conv": ^2.1.2

  "sass": ^1.80.6

  "vue": ^3.5.13
  "vue-tsc": ^2.1.10

  "zod": ^3.23.8

  "typescript": ^5.5.4
  "tsup": ~8.3.5
  "turbo": ^2.3.3

  "vite": ^5.4.10
  "vitest": ^2.1.8
  "@vitejs/plugin-vue": ^5.2.1

  "@changesets/cli": ^2.27.10
