packages:
  - workflow
  - model
  - ui
  - block
  - test

catalog:
  '@platforma-sdk/tengo-builder': ^2.1.3
  '@platforma-sdk/block-tools': ^2.5.47


  '@platforma-sdk/workflow-tengo': ^4.5.0
  '@platforma-sdk/model': ^1.30.26
  '@platforma-sdk/test': ^1.30.34


  '@milaboratories/graph-maker': ^1.1.93
  '@platforma-sdk/ui-vue': ^1.30.26
  '@milaboratories/helpers': ^1.6.11
  '@milaboratories/software-pframes-conv': ^1.5.6

  'sass': ^1.88.0

  'vue': ^3.5.14
  'vue-tsc': ^2.2.10

  'zod': ^3.23.8

  'typescript': ^5.8.3
  'tsup': ~8.3.5
  'turbo': ^2.5.3

  'vite': ^6.3.5
  'vitest': ^3.1.3
  '@vitejs/plugin-vue': ^5.2.4

  '@changesets/cli': ^2.29.4
